# Generated by Django 3.2.12 on 2025-05-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('anno', models.IntegerField(default=2024)),
                ('genero', models.CharField(max_length=250)),
                ('duracion', models.IntegerField(default=0)),
                ('director', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
