# Generated by Django 3.2.12 on 2025-04-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
    ]
