# Generated by Django 3.2.12 on 2025-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20250429_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anno',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
